apiVersion: v1
kind: Service
metadata:
  name: capitals-ui
  namespace: capitals-ui
  labels:
    app: capitals-ui
spec:
  type: NodePort
  selector:
    app: capitals-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31081
      protocol: TCP
